Refactor the database script
CMIPT/gcs-back-end pull request #23
Opened 2024-08-05 16:57 UTC by Quentin9922

In this submission, we reconstructed the database script and divided a sql script into multiple sql scripts with different functions, which reduced the coupling and facilitated subsequent updates.

We also provide `database_deploy.sql` one-click calling script, which can call all creation processes, and use
`psql -U your_username -d your_database -f path_to/database_deploy.sql` command can connect to the specified database and run the script.

See #18.

2024-08-06 02:08 UTC, Kaiser-Yang requested changes

2024-08-15 04:44 UTC, Kaiser-Yang approved these changes

2024-08-15 15:36 UTC, ajiankexx approved these changes

2024-08-15 15:38 UTC, ajiankexx approved these changes
I learn a lot from database_deploy.sh and other sql scripts.

2024-08-16 02:32 UTC, merged